; =============================================
; Hexa - App Dock Configuration
; ???뚯씪???깆쓣 異붽??섎㈃ ?먮룞?쇰줈 ?덈땲肄?諛곗튂?⑸땲??
; =============================================
; ?묒떇:
; AppName_N=???대쫫
; AppPath_N=?ㅽ뻾 寃쎈줈
; AppIcon_N=?꾩씠肄?寃쎈줈 (鍮덇컪?대㈃ 湲곕낯 ?꾩씠肄?
;
; N? 1遺???쒖꽌?濡?利앷?
; AppCount瑜????섏뿉 留욊쾶 ?섏젙

[Variables]
AppCount=3

AppName_1=Google
AppUrl_1=https://www.google.com
AppIcon_1=#@#Icons\google.png

AppName_2=YouTube
AppUrl_2=https://www.youtube.com
AppId_2=agimnkijcaahngcdmfeangaknmldooml
AppIcon_2=#@#Icons\youtube.png

AppName_3=YouTube Music
AppUrl_3=https://music.youtube.com
AppId_3=cinhimbnkkaeohfgghhklpknlkffjgod
AppIcon_3=#@#Icons\YT-music.png
